### ISSUE TITLE
Per-Repository Access Rights to allow access for Outside Collaborators

### ISSUE THREAD

**Issue by hybridherbst** [n4bb12/verdaccio-github-oauth-ui#136]
## Feature Request

From the docs (and from my tests), it looks like currently per-org and per-team access is supported.
Would it be possible to add per-repo? While per-team works for many usecases, per-repo would be better in some cases.

Most relevant usecase there would be that on a per-repository level access can be configured to contain Outside Collaborators, while on a per-team level people are always org members and can't be outside collaborators.

#### Is your feature request related to a problem? Please describe.
Teams can't contain outside collaborators, and thus grouping outside collaborators with access rights in Verdaccio through this plugin is impossible right now (or I'm missing something to configure per-repo access rights).

#### Describe the solution you'd like
Ability to use the same syntax (github/org/stuff) but the latter part could either be a team (as-is) or a repo (new).

#### Describe alternatives you've considered
As far as I can see the alternative would be adding invidual users which also might not be supported (or I couldn't find it); this would kinda defeat the purpose of using a middleware though.

**EDIT:** I _think_ the right place to add something like this would be somewhere around [here](https://github.com/n4bb12/verdaccio-github-oauth-ui/blob/5455fdb471417f39fb37a91d0334a2bd44b48ac1/src/server/plugin/Plugin.ts#L56) or [here](https://github.com/n4bb12/verdaccio-github-oauth-ui/blob/5455fdb471417f39fb37a91d0334a2bd44b48ac1/src/server/plugin/AuthCore.ts#L45); my javascript/typescript knowledge is pretty limited though :(

**Comment by n4bb12** [comment]
Sounds like a good use case.

How would you suggest doing that configuration-wise?

**Comment by hybridherbst** [comment]
Ideally I think the system would just figure out what matches, e.g.

```
github/GITHUB_ORG
github/GITHUB_ORG/GITHUB_TEAM
github/GITHUB_ORG/GITHUB_REPO
github/GITHUB_USER

```
This might mean that there's multiple requests though (not sure what's cached and what not), an alternative would be

```
github/GITHUB_ORG/repo:GITHUB_REPO
github/user:GITHUB_USER
```
or
```
github/GITHUB_ORG/repo/GITHUB_REPO
github/user/GITHUB_USER
```

What do you think?

**Comment by n4bb12** [comment]
The thing with teams and repos is that they don't share namespaces. One could create a repository named the same as a certain team and thereby gain access to the packages only that team is supposed to have access to.

`github/GITHUB_USER` works because orgs and usernames share the same name pool, hence it's not possible to forge a collision.

**Comment by hybridherbst** [comment]
I think the safest way would be to explicitly specify
github/GITHUB_ORG/repo:GITHUB_REPO which can't be a path then?

**Comment by n4bb12** [comment]
That should work. I like the `github/GITHUB_ORG/repo/GITHUB_REPO` variant because it's a little bit easier splitting.

**Comment by hybridherbst** [comment]
Thank you! Looking forward to this :)

**Comment by hybridherbst** [comment]
Do you think you might get to this anytime soon? Especially the per-repo access part. 
If not, no problem, just trying to understand if I should set up things with teams in the meantime or can wait a bit :)

**Comment by n4bb12** [comment]
https://github.com/n4bb12/verdaccio-github-oauth-ui/releases/tag/3.1.0

Please let me know if you encounter any issues.

**Comment by n4bb12** [comment]
Outside collaborators don't work yet because org membership is currently a hard login requirement.
See https://github.com/n4bb12/verdaccio-github-oauth-ui/blob/master/src/server/plugin/AuthCore.ts#L46.

We could question if an org membership is really necessary. Access to packages can be restricted independently of the login. Users that are not part of a certain org could be able to log in but simply not see anything and not have access to anything.

But the current semantics are that `$authenticated` refers to members of the org configured in the plugin options. See https://github.com/n4bb12/verdaccio-github-oauth-ui#org-required. Lifting this requirement would unfortunately be a breaking change.

Maybe we could make the org option optional. Currently, it's required. If it is configured, it's a login requirement, if not, everybody can log in and only the package configuration restricts access. That might be a way to keep things backward compatible.

What do you think?

**Comment by hybridherbst** [comment]
Yes, I think making it optional sounds right (I thought it was only used to get the secret etc to route to the right request, I didn't expect it to already control access).

Besides allowing outside collaborators, this also would allow adding specific other orgs to specific access controls, which I thought was already possible and we were planning to use anyways - so good find 🙂

**Comment by hybridherbst** [comment]
Hah, seems this is a can of worms, private repos seem to only be included if the scope contains "repo", there's no "repo:read", and "org:read" doesn't seem to return private repos at all.

**Comment by n4bb12** [comment]
> private repos seem to only be included if the requested OAuth scope contains "repo"

Good catch! I fixed this (https://github.com/n4bb12/verdaccio-github-oauth-ui/commit/eef7d995203df7a13b94032ce047c44730758e26) and made a release ([3.1.1](https://github.com/n4bb12/verdaccio-github-oauth-ui/releases/tag/3.1.1)).

However, this of course makes https://github.com/n4bb12/verdaccio-github-oauth-ui/issues/139 worse since the list now gets even longer.

**Comment by hybridherbst** [comment]
Thank you! - so making the group optional might be the last step remaining for this, right?

**Comment by n4bb12** [comment]
Yes, currently working on it. 😀

**Comment by hybridherbst** [comment]
Awesome - let me know when you have something to test!

**Comment by n4bb12** [comment]
Here you go https://github.com/n4bb12/verdaccio-github-oauth-ui/releases/tag/3.2.0
See the updated configuration docs https://github.com/n4bb12/verdaccio-github-oauth-ui#verdaccio-config
